FROM node:25-alpine3.22

WORKDIR /app

COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src

RUN ls -a
RUN npm install && npm install -g nodemon

EXPOSE 4002

CMD ["npm", "run", "dev"]