@baseUrl = https://jobberemre.com
@urlPath = api/gateway/v1


###
PUT {{baseUrl}}/{{urlPath}}/auth/seeds/10
Content-Type: application/json
Accept: application/json


###
PUT {{baseUrl}}/{{urlPath}}/seller/seed/10
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
# Gig seed - Auth gerekir (önce login ol)
GET {{baseUrl}}/{{urlPath}}/gig/seed/10
Content-Type: application/json
Accept: application/json
withCredentials: true