apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: production
data:
  kibana.yml: |
    server.host: '0.0.0.0'
    server.port: 5601
    server.name: 'kibana'

    elasticsearch.hosts: ['http://jobber-elastic.production.svc.cluster.local:9200']

    i18n.locale: 'en'

    elasticsearch.requestTimeout: 30000
    elasticsearch.pingTimeout: 30000
    xpack.fleet.enabled: true
    xpack.fleet.agents.enabled: true
    xpack.fleet.agents.elasticsearch.hosts: ['http://jobber-elastic.production.svc.cluster.local:9200']
    xpack.reporting.roles.enabled: true
    xpack.fleet.agentIdVerificationEnabled: true
    xpack.security.encryptionKey: AAEAAWVsYXN0aWMva2liYW5hL2pvYmJlci1raWJhbmE6dkliU0dUdVhTU2VVVndJNEFLU0tYUQ
    xpack.encryptedSavedObjects.encryptionKey: AAEAAWVsYXN0aWMva2liYW5hL2pvYmJlci1raWJhbmE6dkliU0dUdVhTU2VVVndJNEFLU0tYUQ

    xpack.fleet.packages:
      - name: apm
        version: latest
    xpack.fleet.agentPolicies:
      - name: Agent policy 1
        id: agent-policy-1
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        package_policies:
          - name: apm-1
            id: default-apm
            package:
              name: apm
