apiVersion: v1
kind: Service
metadata:
  name: jobber-queue
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: jobber-queue
  ports:
    - name: queue
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: management
      port: 15672
      targetPort: 15672
      protocol: TCP
